---
title: "À propos"
subtitle: "Alternant à l'INSEE, j'apprécie travailler sur des sujets complexes en utilisant des méthodes statistiques."
lang: "fr"
---

## Formation

::: {.callout-note icon="false" appearance="default"}
## IUT de Paris - Rives de Seine (Université Paris Cité) \| Paris, France

Bachelor universitaire de technologie en **Science des données** \| Sept 2022 - Juin 2025\
**Cours suivis** : Algèbre, Statistique, Probabilités, Programmation, Base de données, Économie
:::

## Expérience

::: {.callout-important icon="false" appearance="default"}
## Institut national de la statistique et des études économiques (INSEE) \| Montrouge, France

**Programmeur Statistique** \| 2023 - 2025<br> Au sein de la Direction des statistiques démographiques et sociales, j'ai mené des travaux d'appariement de données administratives. L'objectif de ces travaux était de mesurer et de comparer la couverture de deux bases de sondages. Par ailleurs, j'ai comparé différents algorithmes d'appariement à l'aide d'analyses statistiques.

Mes missions ont inclus la **manipulation de données brutes**, le **nettoyage des données**, l'appariement de grands **volumes de données**, ainsi que leur **analyse statistique**.
:::

## Compétences

::: {.callout-tip icon="false" appearance="default"}
## Programmation

Python \| R \| SQL \| SAS \| GIT
:::

::: {.callout-warning icon="false" appearance="default"}
## Langue

Anglais (**B2**) \| Espagnol (**B2**) \| Arabe (**C2**)
:::
